# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iptu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_contrib', models.CharField(max_length=12, unique=True, verbose_name='nº contribuinte')),
                ('ano_exerc', models.CharField(max_length=4, verbose_name='ano exercício')),
                ('num_nl', models.CharField(max_length=1, verbose_name='num. nl')),
                ('data_cadastro', models.DateField(verbose_name='data cadastramento')),
                ('tipo_contrib_1', models.CharField(max_length=22, verbose_name='Tipo contribuinte 1')),
                ('doc_contrib_1', models.CharField(max_length=14, verbose_name='CPF/CNPJ contribuinte 1')),
                ('nome_contrib_1', models.CharField(max_length=255, verbose_name='nome contribuinte 1')),
                ('tipo_contrib_2', models.CharField(blank=True, max_length=22, verbose_name='Tipo Contribuinte 2')),
                ('doc_contrib_2', models.CharField(blank=True, max_length=14, verbose_name='CPF/CNPJ contribuinte 2')),
                ('nome_contrib_2', models.CharField(blank=True, max_length=255, verbose_name='nome contribuinte 2')),
                ('num_condominio', models.CharField(max_length=10, verbose_name='nº condomínio')),
                ('codlog_imovel', models.CharField(max_length=10, verbose_name='CODLOG do imóvel')),
                ('logradouro_imovel', models.CharField(max_length=255, verbose_name='logradouro imóvel')),
                ('num_imovel', models.IntegerField(verbose_name='nº do imóvel')),
                ('complemento_imovel', models.CharField(blank=True, max_length=255, verbose_name='complemento')),
                ('bairro_imovel', models.CharField(blank=True, max_length=255, verbose_name='bairro')),
                ('ref_imovel', models.CharField(blank=True, max_length=255, verbose_name='referência')),
                ('cep_imovel', models.CharField(max_length=9, verbose_name='CEP')),
                ('esq_frente', models.IntegerField(verbose_name='nº esquina/frente')),
                ('fracao_ideal', models.FloatField(verbose_name='fração ideal')),
                ('area_terreno', models.IntegerField(verbose_name='area do terreno')),
                ('area_contruida', models.IntegerField(verbose_name='area construída')),
                ('area_ocupada', models.IntegerField(verbose_name='area ocupada')),
                ('valor_m2_terreno', models.FloatField(verbose_name='valor m2 terreno')),
                ('valor_m2_construido', models.FloatField(verbose_name='valor m2 construído')),
                ('ano_construcao', models.CharField(max_length=4, verbose_name='ano construção')),
                ('qde_pavimentos', models.IntegerField(verbose_name='qde pavimentos')),
                ('testada_calculo', models.FloatField(verbose_name='testada para cálculo')),
                ('tipo_uso', models.CharField(max_length=255, verbose_name='tipo uso')),
                ('tipo_construcao', models.CharField(max_length=255, verbose_name='tipo padrão construção')),
                ('tipo_terreno', models.CharField(max_length=255, verbose_name='tipo terreno')),
                ('fator_obsolencia', models.FloatField(verbose_name='fator obsolencia')),
                ('ano_inicio_vida_contrib', models.CharField(max_length=4, verbose_name='ano início vida contribuinte')),
                ('mes_inicio_vida_contrib', models.CharField(max_length=2, verbose_name='mês início vida contribuinte')),
                ('fase_contrib', models.IntegerField(verbose_name='fase contribuinte')),
            ],
        ),
    ]
