# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lista_nomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('sobrenome', models.CharField(max_length=255, verbose_name='sobrenome')),
                ('email', models.EmailField(max_length=75, verbose_name='email')),
            ],
        ),
    ]
