# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lista_nomes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lista_nomes',
        ),
        migrations.AlterModelOptions(
            name='iptu',
            options={'verbose_name': 'IPTU', 'verbose_name_plural': 'IPTU'},
        ),
    ]
