# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171218_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptu',
            name='num_contrib',
            field=models.CharField(max_length=24, unique=True, verbose_name='nº contribuinte'),
        ),
    ]
