# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20171219_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iptu',
            options={'ordering': ['num_contrib'], 'verbose_name': 'IPTU', 'verbose_name_plural': 'IPTU'},
        ),
        migrations.AlterField(
            model_name='iptu',
            name='nome_contrib_1',
            field=models.CharField(max_length=255, verbose_name='nome contribuinte'),
        ),
    ]
