# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20171219_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iptu',
            name='id',
        ),
        migrations.AlterField(
            model_name='iptu',
            name='num_contrib',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='nº contribuinte'),
        ),
    ]
